trigger:
- main  # Set the branch you want to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux agent
  demands:
   - agent.name: defualt

steps:
- script: |
    # Install Ansible if it's not already installed
    sudo apt-get update -y
    sudo apt-get install -y ansible

    # Clone the Git repository
    git clone https://github.com/hemakumar901/creating-vm.git


    # Run the Ansible playbook
    ansible-playbook virtualmachine.yml
  displayName: 'Run Ansible Playbook'
