trigger:
  - main  # Replace with the branch you want to trigger the pipeline on

pr:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Starting Ansible playbook execution"
    ansible-playbook virtualmachine.yml
  displayName: 'Run Ansible Playbook'