# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'  # Choose an agent that supports Ansible

steps:
- script: |
    # Install Ansible
    pip install ansible

    # Run the Ansible playbook
    ansible-playbook  creating-vm
/virtual machine.yml
  displayName: 'Run Ansible Playbook'
